name: Publish image to Docker Hub
on: 
  [wokflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          docker build . -t javeedambu/hello-docker-hub:latest
      - name: Publish
        run: |
          docker push javeedambu/hello-docker-hub:latest

